### PR TITLE
add LLM post

### PR DESCRIPTION
**Pull request by naik-aakash**
Hi @JaGeo  and @kaueltzen , can you please have a look at this short post I added and let me know if it is fine.

### CODE REVIEW

**Comment by JaGeo** [comment]
Could you add an additional small picture to the post? Currently, my face is shown again

**Comment by naik-aakash** [comment]
> Could you add an additional small picture to the post? Currently, my face is shown again

Changed it. Forgot to change it before

**Comment by JaGeo** [comment]
Can you make a second pull request? This one is already merged. Sorry!

**Comment by naik-aakash** [comment]
Raised now

**Pull request merged**
